// Komplain.ai — demo data + simulated SSE pipelines

window.SCENARIOS = [
  {
    key: 'manglish',
    label: 'Manglish / delivery',
    blurb: 'Mixed BM+EN slang, 14-day delay',
    complaint: "Brader, barang saya tak sampai lagi la. Dah 2 minggu tracking still processing je. Mana pergi barang saya ni? Order ORD-2041. Kalau tak settle hari ni, I nak refund balik.",
    orderId: 'ORD-2041',
  },
  {
    key: 'clean',
    label: 'Clean refund',
    blurb: 'EN, damaged item within policy',
    complaint: "Hi, I received my order ORD-1887 but the item is damaged. The dress has a torn seam on the side. I'd like a replacement or refund please.",
    orderId: 'ORD-1887',
  },
  {
    key: 'edge',
    label: 'Missing order ID',
    blurb: 'BM, no order reference — edge case',
    complaint: "Saya nak refund. Barang rosak.",
    orderId: '',
  },
];

window.MOCK_ORDERS = {
  'ORD-2041': {
    id: 'ORD-2041',
    product_name: 'Baju Kurung Moden — Maroon XL',
    order_date: '2026-04-07',
    delivery_status: 'delayed',
    days_since_order: 14,
    seller_policy_refund_days: 30,
    seller_policy_reship_allowed: true,
    courier: 'J&T Express',
    tracking: 'JT9421780041MY',
  },
  'ORD-1887': {
    id: 'ORD-1887',
    product_name: 'Linen Midi Dress — Sage M',
    order_date: '2026-04-18',
    delivery_status: 'delivered',
    days_since_order: 3,
    seller_policy_refund_days: 7,
    seller_policy_reship_allowed: true,
    courier: 'Ninja Van',
    tracking: 'NV77812HC',
  },
};

// Pre-built case log with prior resolved cases so the table feels populated
window.SEED_CASES = [
  {
    id: 'CMP-24A8',
    preview: 'Ninjavan hantar salah alamat — barang sampai rumah sebelah…',
    resolution: 'RESHIP',
    confidence: 0.92,
    status: 'resolved',
    timestamp: '2026-04-20 16:42',
    order: 'ORD-2036',
    lang: 'BM',
  },
  {
    id: 'CMP-24A7',
    preview: 'Received wrong colour — ordered navy, got grey. Very disappointed.',
    resolution: 'RESHIP',
    confidence: 0.89,
    status: 'resolved',
    timestamp: '2026-04-20 14:10',
    order: 'ORD-2034',
    lang: 'EN',
  },
  {
    id: 'CMP-24A6',
    preview: 'Item tak sama dengan gambar. Warna lain, material pun cheap.',
    resolution: 'REFUND',
    confidence: 0.76,
    status: 'review',
    timestamp: '2026-04-20 11:05',
    order: 'ORD-2029',
    lang: 'BM',
  },
  {
    id: 'CMP-24A5',
    preview: 'Customer abusive, demanding full refund 3 months after delivery.',
    resolution: 'DISMISS',
    confidence: 0.94,
    status: 'resolved',
    timestamp: '2026-04-19 21:33',
    order: 'ORD-1912',
    lang: 'EN',
  },
  {
    id: 'CMP-24A4',
    preview: 'Package visibly damaged on arrival — photo attached to email.',
    resolution: 'ESCALATE',
    confidence: 0.71,
    status: 'review',
    timestamp: '2026-04-19 18:20',
    order: 'ORD-2014',
    lang: 'EN',
  },
];

// Each scenario: array of events. Times are relative ms from Resolve click.
// Each event -> { at, agent, status, message, output? }
window.PIPELINES = {
  manglish: {
    resolution: {
      type: 'REFUND',
      confidence: 0.91,
      reason: 'Order ORD-2041 has been in processing state for 14 days with no tracking movement. Seller\'s 30-day refund window is in force and there is no evidence of delivery. Customer frustration level is high; refund is the least-friction resolution.',
      policy: 'Consumer Protection (Electronic Trade) Regulations 2024 · §12(3) — undelivered goods after reasonable period',
      response_en: "Hi there,\n\nThanks for reaching out about order ORD-2041. I can see that your Baju Kurung Moden (Maroon, XL) has been stuck in processing for 14 days with no movement from J&T — that's not acceptable and I'm sorry for the wait.\n\nI've authorised a full refund of RM 89.00, which will be returned to your original payment method within 3–5 business days. No need to send anything back.\n\nIf the parcel does eventually arrive, please keep it as our apology.\n\n— Nadia, Sambal & Silk",
      response_bm: "Hai,\n\nTerima kasih kerana hubungi kami tentang pesanan ORD-2041. Kami sedar Baju Kurung Moden (Maroon, XL) anda telah tersangkut di status 'processing' selama 14 hari tanpa sebarang pergerakan dari J&T — kami memohon maaf atas kelewatan ini.\n\nKami telah memproses refund penuh sebanyak RM 89.00, dan ia akan dikembalikan ke kaedah pembayaran asal dalam masa 3–5 hari bekerja. Anda tidak perlu pulangkan apa-apa.\n\nSekiranya bungkusan akhirnya tiba, sila simpan sebagai tanda maaf kami.\n\n— Nadia, Sambal & Silk",
      amount: 'RM 89.00',
      requires_review: false,
    },
    events: [
      { at: 120, agent: 'supervisor', status: 'running', message: 'Pipeline initialised · GLM-4 · trace-id trc_2047ab' },
      { at: 240, agent: 'intake', status: 'started', message: 'Reading complaint · 247 chars' },
      { at: 620, agent: 'intake', status: 'running', message: 'Detecting language...', detail: 'Manglish tokens: brader, la, je, settle' },
      { at: 980, agent: 'intake', status: 'running', message: 'Extracting intent + urgency' },
      { at: 1340, agent: 'intake', status: 'completed', message: 'Intake complete · urgency 4/5', output: {
        complaint_type: 'delivery_delay',
        sentiment: 'frustrated',
        urgency_score: 4,
        extracted_order_id: 'ORD-2041',
        language_detected: 'Manglish (BM+EN)',
        summary_en: 'Customer reports parcel stuck in processing for 2 weeks; threatens refund if unresolved today.'
      }},
      { at: 1480, agent: 'context', status: 'started', message: 'Fetching order ORD-2041' },
      { at: 1820, agent: 'context', status: 'running', message: 'Joining orders · seller_policies · tracking' },
      { at: 2240, agent: 'context', status: 'completed', message: 'Order found · delayed 14d', output: {
        order_id: 'ORD-2041',
        product: 'Baju Kurung Moden — Maroon XL',
        delivery_status: 'delayed',
        days_since_order: 14,
        courier: 'J&T Express',
        tracking_last_scan: '2026-04-07 09:12 KUL Hub',
        refund_window_days: 30,
        within_policy: true,
      }},
      { at: 2380, agent: 'reasoning', status: 'started', message: 'Applying GLM reasoning chain' },
      { at: 2780, agent: 'reasoning', status: 'running', message: 'Step 1/4 · Is complaint valid?' },
      { at: 3180, agent: 'reasoning', status: 'running', message: 'Step 2/4 · What does evidence support?' },
      { at: 3580, agent: 'reasoning', status: 'running', message: 'Step 3/4 · Consumer Protection Regs 2024 §12' },
      { at: 3940, agent: 'reasoning', status: 'running', message: 'Step 4/4 · Selecting resolution' },
      { at: 4340, agent: 'reasoning', status: 'completed', message: 'Decision · REFUND · conf 0.91', output: {
        resolution_type: 'REFUND',
        confidence_score: 0.91,
        policy_reference: 'Consumer Protection (Electronic Trade) Regs 2024, §12(3)',
        reason: 'No evidence of delivery; within 30-day window; customer tenure low tolerance.',
      }},
      { at: 4500, agent: 'response', status: 'started', message: 'Drafting bilingual reply' },
      { at: 4920, agent: 'response', status: 'running', message: 'Tone-matching · empathetic, BM-first' },
      { at: 5320, agent: 'response', status: 'completed', message: 'EN + BM drafts ready', output: {
        response_en_preview: "Hi there, Thanks for reaching out about order ORD-2041...",
        response_bm_preview: "Hai, Terima kasih kerana hubungi kami tentang pesanan ORD-2041...",
      }},
      { at: 5460, agent: 'supervisor', status: 'completed', message: 'Pipeline resolved · 5.34s total · 4/4 agents OK' },
    ],
  },
  clean: {
    resolution: {
      type: 'RESHIP',
      confidence: 0.95,
      reason: 'Item delivered 3 days ago with reported damage. Seller policy permits reshipping within 7-day window. Reshipping is preferred over refund per seller\'s stated policy because inventory is in stock and customer expressed openness to replacement.',
      policy: 'Sambal & Silk · Damage Policy §2.1 — reship preferred within 7 days',
      response_en: "Hi,\n\nThank you for letting us know about ORD-1887. I'm really sorry the Linen Midi Dress arrived with a torn seam — that absolutely shouldn't happen.\n\nI've arranged for a replacement in the same size and colour to be shipped out today on Ninja Van. You should receive it within 2–3 working days. No need to return the damaged piece.\n\nWe'll include a small thank-you with your replacement.\n\n— Nadia, Sambal & Silk",
      response_bm: "Hai,\n\nTerima kasih kerana memaklumkan kami tentang ORD-1887. Kami mohon maaf kerana Linen Midi Dress anda sampai dengan jahitan yang koyak — ini tidak sepatutnya berlaku.\n\nSaya telah mengatur penghantaran gantian dalam saiz dan warna yang sama, akan dihantar hari ini melalui Ninja Van. Anda akan menerimanya dalam 2–3 hari bekerja. Anda tidak perlu pulangkan barang yang rosak.\n\nKami akan sertakan sedikit tanda terima kasih bersama penggantian anda.\n\n— Nadia, Sambal & Silk",
      amount: '1 × replacement',
      requires_review: false,
    },
    events: [
      { at: 120, agent: 'supervisor', status: 'running', message: 'Pipeline initialised · GLM-4 · trace-id trc_2047ac' },
      { at: 240, agent: 'intake', status: 'started', message: 'Reading complaint · 164 chars' },
      { at: 560, agent: 'intake', status: 'running', message: 'Detecting language · EN' },
      { at: 920, agent: 'intake', status: 'completed', message: 'Intake complete · urgency 3/5', output: {
        complaint_type: 'damage',
        sentiment: 'neutral',
        urgency_score: 3,
        extracted_order_id: 'ORD-1887',
        language_detected: 'English',
        summary_en: 'Customer reports torn seam on received dress; open to replacement or refund.',
      }},
      { at: 1080, agent: 'context', status: 'started', message: 'Fetching order ORD-1887' },
      { at: 1480, agent: 'context', status: 'completed', message: 'Order found · delivered 3d ago', output: {
        order_id: 'ORD-1887',
        product: 'Linen Midi Dress — Sage M',
        delivery_status: 'delivered',
        days_since_order: 3,
        refund_window_days: 7,
        reship_allowed: true,
        within_policy: true,
      }},
      { at: 1640, agent: 'reasoning', status: 'started', message: 'Applying GLM reasoning chain' },
      { at: 2040, agent: 'reasoning', status: 'running', message: 'Evaluating reship vs refund' },
      { at: 2540, agent: 'reasoning', status: 'completed', message: 'Decision · RESHIP · conf 0.95', output: {
        resolution_type: 'RESHIP',
        confidence_score: 0.95,
        policy_reference: 'Seller damage policy §2.1',
        reason: 'In-stock, within window, customer open to replacement.',
      }},
      { at: 2700, agent: 'response', status: 'started', message: 'Drafting bilingual reply' },
      { at: 3240, agent: 'response', status: 'completed', message: 'EN + BM drafts ready' },
      { at: 3380, agent: 'supervisor', status: 'completed', message: 'Pipeline resolved · 3.26s total · 4/4 agents OK' },
    ],
  },
  edge: {
    resolution: {
      type: 'CLARIFY',
      confidence: 0.62,
      reason: 'Complaint asserts damage and requests refund but contains no order reference. Intake Agent could not extract an order ID; Context Agent cannot enrich without one. Supervisor intercepted and generated a bilingual clarification request rather than forcing a low-confidence resolution.',
      policy: 'Supervisor fallback · missing_context handler',
      response_en: "Hi,\n\nThanks for getting in touch. I can see you'd like a refund because the item arrived damaged — I'm sorry about that.\n\nTo pull up your order and process this quickly, could you share your order number (starts with ORD-)? You can find it in your confirmation email or your account under 'My Orders'.\n\nOnce I have that, I'll sort this out straight away.\n\n— Nadia, Sambal & Silk",
      response_bm: "Hai,\n\nTerima kasih kerana menghubungi kami. Saya faham anda ingin refund kerana barang yang diterima rosak — kami mohon maaf atas keadaan ini.\n\nUntuk membantu kami menyemak pesanan anda dengan cepat, boleh kongsikan nombor pesanan anda (bermula dengan ORD-)? Anda boleh temuinya dalam email pengesahan atau di akaun anda di bawah 'My Orders'.\n\nSetelah kami terima nombor tersebut, kami akan uruskan dengan segera.\n\n— Nadia, Sambal & Silk",
      amount: '—',
      requires_review: true,
    },
    events: [
      { at: 120, agent: 'supervisor', status: 'running', message: 'Pipeline initialised · GLM-4 · trace-id trc_2047ad' },
      { at: 240, agent: 'intake', status: 'started', message: 'Reading complaint · 32 chars' },
      { at: 560, agent: 'intake', status: 'running', message: 'Detecting language · BM' },
      { at: 920, agent: 'intake', status: 'completed', message: 'Intake complete · no order_id', output: {
        complaint_type: 'damage',
        sentiment: 'neutral',
        urgency_score: 2,
        extracted_order_id: null,
        language_detected: 'Bahasa Malaysia',
        summary_en: 'Customer requests refund due to damaged item; no order reference provided.',
      }},
      { at: 1080, agent: 'context', status: 'started', message: 'Lookup attempt · order_id=null' },
      { at: 1420, agent: 'context', status: 'failed', message: 'No order_id → context unavailable', output: {
        context_available: false,
        reason: 'No extractable order ID; no alternate identifiers (email, phone) present.',
      }},
      { at: 1560, agent: 'supervisor', status: 'running', message: 'Intercept · engaging clarification flow' },
      { at: 1920, agent: 'reasoning', status: 'started', message: 'Mode · clarify (no context)' },
      { at: 2320, agent: 'reasoning', status: 'completed', message: 'Needs order_id · bilingual prompt', output: {
        resolution_type: 'CLARIFY',
        confidence_score: 0.62,
        reason: 'Insufficient information to decide without order reference.',
      }},
      { at: 2480, agent: 'response', status: 'started', message: 'Drafting clarification · BM + EN' },
      { at: 2980, agent: 'response', status: 'completed', message: 'Clarification ready · requires review' },
      { at: 3120, agent: 'supervisor', status: 'completed', message: 'Pipeline resolved · status PENDING_INFO · no crash' },
    ],
  },
};

window.AGENTS = [
  { key: 'intake',    name: 'Intake Agent',    role: 'Parses raw complaint · extracts intent, language, urgency' },
  { key: 'context',   name: 'Context Agent',   role: 'Enriches with order data · policy · delivery status' },
  { key: 'reasoning', name: 'Reasoning Agent', role: 'GLM core · applies multi-step policy reasoning' },
  { key: 'response',  name: 'Response Agent',  role: 'Drafts bilingual EN + BM reply · matches tone' },
];
